Post users
rodrossi/Chronos-BackEnd pull request #3
Opened 2020-02-05 16:42 UTC by Hsaraujo-98

@rodrossi , @JeffeSouza , @samucaopcao , @LR-Developer , @KenzoII
Time, boa tarde.

Favor analisar o método para cadastro de usuário (post-users).

Att,
Hugo Souza.

2020-02-05 19:04 UTC, LR-Developer requested changes
:no_entry_sign: 
Favor efetuar a correção solicitada.

2020-02-05 19:04 UTC, LR-Developer commented on br.com.chronos/src/main/java/br/com/chronos/services/UserService.java
> +
Remover esse "TAB" presente na linha 19.

2020-02-12 13:27 UTC, rodrossi approved these changes

2020-02-12 13:27 UTC, LR-Developer approved these changes
Aprovado!
:shipit:

2020-02-12 13:46 UTC, merged