Update users
rodrossi/Chronos-BackEnd pull request #4
Opened 2020-02-05 18:50 UTC by samucaopcao

2020-02-06 12:35 UTC, KenzoIshii submitted a review, later dismissed
:shipit:

2020-02-06 13:32 UTC, rodrossi commented on br.com.chronos/src/main/java/br/com/chronos/domain/User.java
> +		//command.validate();
Favor Verificar comentário no código

2020-02-06 13:41 UTC, rodrossi requested changes
Favor verificar os apontamentos

2020-02-06 13:41 UTC, rodrossi commented on br.com.chronos/src/main/java/br/com/chronos/domain/User.java
> -
favor remover linha a mais

2020-02-12 13:53 UTC, rodrossi approved these changes
Aprovado 
:shipit:

2020-02-12 13:55 UTC, KenzoIshii approved these changes
:shipit:

2020-02-12 18:13 UTC, merged